# Generated by Django 4.2 on 2026-01-13 13:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_options'),
        ('portfolios', '0003_rebalancelog_portfoliosnapshot_dividendlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosnapshot',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('REBALANCE', 'Rebalance'), ('SWITCH', 'Strategy Switch')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
