# Generated by Django 4.2 on 2026-01-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_options'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='executed_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='trade',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('REBALANCE', 'Rebalance'), ('SWITCH', 'Strategy Switch')], max_length=20),
        ),
    ]
