# Generated by Django 4.2 on 2026-01-10 13:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('REIT', 'REIT')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('volatility', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
