# Generated by Django 4.2 on 2026-01-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='annual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual dividend yield (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True),
        ),
    ]
