# Generated by Django 4.2 on 2026-01-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_annual_yield_asset_dividend_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['symbol']},
        ),
    ]
