# Generated by Django 4.2 on 2026-01-15 14:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_portfoliosnapshot_options_transaction'),
        ('copytrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradePnL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_pnls', to='portfolios.portfolio')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_copy_pnls', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('follower', 'leader')},
            },
        ),
    ]
