# Generated by Django 4.2 on 2026-01-17 15:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrelationship',
            name='allocated_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
    ]
